"""Updated model Recipe with different links for different images

Revision ID: 4c86ad8d8836
Revises: a45295bb29e1
Create Date: 2025-03-21 15:27:40.350785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c86ad8d8836'
down_revision = 'a45295bb29e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_image_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('quality_img_URL', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('compressed_img_URL', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_path')
        batch_op.drop_column('public_URL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_URL', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('compressed_img_URL')
        batch_op.drop_column('quality_img_URL')
        batch_op.drop_column('local_image_path')

    # ### end Alembic commands ###
