"""Added MenuShoppingInfo table

Revision ID: 95c12287d94b
Revises: f772441e9755
Create Date: 2025-04-28 15:32:33.270977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c12287d94b'
down_revision = 'f772441e9755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_shopping_infos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_tag_id', sa.Integer(), nullable=False),
    sa.Column('shopping_list_text', sa.Text(), nullable=True),
    sa.Column('preparations_text', sa.Text(), nullable=True),
    sa.Column('meat_marinades_text', sa.Text(), nullable=True),
    sa.Column('dressings_text', sa.Text(), nullable=True),
    sa.Column('rules_and_tips_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['menu_tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_shopping_infos')
    # ### end Alembic commands ###
