"""Updated Recipes to have public URL

Revision ID: a45295bb29e1
Revises: 70554226ae3d
Create Date: 2025-03-20 19:00:22.220056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45295bb29e1'
down_revision = '70554226ae3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_URL', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('public_URL')

    # ### end Alembic commands ###
