"""Added indexing and vectors

Revision ID: b834a7f04de0
Revises: 4c86ad8d8836
Create Date: 2025-04-02 11:20:50.315138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b834a7f04de0'
down_revision = '4c86ad8d8836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_search', postgresql.TSVECTOR(), nullable=True))
        batch_op.create_index('ix_ingredients_name_search', ['name_search'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instruction_search', postgresql.TSVECTOR(), nullable=True))
        batch_op.create_index('ix_instructions_instruction_search', ['instruction_search'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_search', postgresql.TSVECTOR(), nullable=True))
        batch_op.create_index('ix_recipes_title_search', ['title_search'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index('ix_recipes_title_search', postgresql_using='gin')
        batch_op.drop_column('title_search')

    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.drop_index('ix_instructions_instruction_search', postgresql_using='gin')
        batch_op.drop_column('instruction_search')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index('ix_ingredients_name_search', postgresql_using='gin')
        batch_op.drop_column('name_search')

    # ### end Alembic commands ###
