"""Add index to name column in tags and ingredients

Revision ID: bb09ee9ed283
Revises: b834a7f04de0
Create Date: 2025-04-02 11:44:22.990256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb09ee9ed283'
down_revision = 'b834a7f04de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index('ix_ingredients_name', ['name'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('ix_tags_name', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tags_name')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index('ix_ingredients_name')

    # ### end Alembic commands ###
