"""Add user recipe notes

Revision ID: e7e5757e0193
Revises: bb09ee9ed283
Create Date: 2025-04-13 19:26:14.299728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e5757e0193'
down_revision = 'bb09ee9ed283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recipe_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uix_user_recipe')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index('idx_name_search', postgresql_using='gin')

    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.drop_index('idx_instruction_search', postgresql_using='gin')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index('idx_title_search', postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index('idx_title_search', ['title_search'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.create_index('idx_instruction_search', ['instruction_search'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index('idx_name_search', ['name_search'], unique=False, postgresql_using='gin')

    op.drop_table('user_recipe_notes')
    # ### end Alembic commands ###
