"""Make tag name unique per type

Revision ID: f772441e9755
Revises: e7e5757e0193
Create Date: 2025-04-18 14:54:42.936687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f772441e9755'
down_revision = 'e7e5757e0193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('tags_name_key', type_='unique')
        batch_op.create_unique_constraint('uix_tag_name_type', ['name', 'type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('uix_tag_name_type', type_='unique')
        batch_op.create_unique_constraint('tags_name_key', ['name'])

    # ### end Alembic commands ###
